<a href="https://colab.research.google.com/github/MahmoudEl-sherbiny/DEPI/blob/main/Pandas_Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# üêº Pandas Practice: DataFrames, Selection, Mapping, and More

In [68]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Sample data
names = ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah']
departments = ['Sales', 'Marketing', 'HR', 'Tech']

# Create a DataFrame
df = pd.DataFrame({
    'Name': np.random.choice(names, size=20),
    'Age': np.random.randint(22, 60, size=20),
    'Department': np.random.choice(departments, size=20),
    'Salary': np.random.randint(40000, 120000, size=20),
    'YearsExperience': np.random.randint(0, 20, size=20)
})
df.head()

      Name  Age Department  Salary  YearsExperience
0   George   43         HR   75920               15
1    Diana   23  Marketing  107121               12
2    Ethan   45       Tech  109479               17
3   George   51      Sales   59457               14
4  Charlie   59       Tech  106557               12

# üß™ PRACTICE QUESTIONS BELOW


# 1Ô∏è‚É£ Use .loc to select all rows where the Department is 'Tech'.
#    - Describe what .loc does and why it's useful for label-based filtering.

In [69]:
df.loc[df["Department"]== 'Tech']

       Name  Age Department  Salary  YearsExperience
2     Ethan   45       Tech  109479               17
4   Charlie   59       Tech  106557               12
12  Charlie   49       Tech  111211               11
13  Charlie   37       Tech  105697                7
15    Ethan   24       Tech   72606               18
17   Hannah   28       Tech   80397                7
19  Charlie   30       Tech   95591                2

.loc : It allows you to select rows and columns by their labels (names)

Why it useful?
1. Readable: It makes your code more intuitive by using **column names** and row labels directly.

2. Flexible: You can **filter rows and select specific columns at the same time**
3. Supports complex conditions


# 2Ô∏è‚É£ Use .iloc to select the first 5 rows and the last two columns.
#    - What is the difference between .loc and .iloc?

In [70]:
df.iloc[:5, -2:]

   Salary  YearsExperience
0   75920               15
1  107121               12
2  109479               17
3   59457               14
4  106557               12

# .loc   (Label-Based Filtering)
1. Based on Labels "Names"
2. Can use Condition
3. df.loc[row_labels, col_labels]

# .iloc  (integer-position-based access)
1. Based on Integer  Positions "Index numbers"
2. Not directly with boolean conditions
3. df.iloc[row_positions, col_positions]


# 3Ô∏è‚É£ Map a new column called 'DeptCode' where:
#     'Sales' -> 1, 'Marketing' -> 2, 'HR' -> 3, 'Tech' -> 4.
#    - Use .map and explain what happens if a value is not mapped.

In [71]:
dept_mapping = {
    'Sales': 1,
    'Marketing': 2,
    'HR': 3,
    'Tech': 4
}

df['DeptCode'] = df['Department'].map(dept_mapping)

.map() will assign NaN to that row in 'DeptCode' if a value isnot mapped.


# 4Ô∏è‚É£ Use .apply to calculate a new column 'Seniority' where:
#     - If YearsExperience > 10 ‚Üí 'Senior'
#     - If between 5-10 ‚Üí 'Mid-Level'
#     - Else ‚Üí 'Junior'
#    - Use a lambda function with apply.

In [72]:
df["Seniority"] = df["YearsExperience"].apply(lambda x: "Senior" if x > 10 else "Mid-Level" if x in range(5,11) else "Junior" )
df

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
1     Diana   23  Marketing  107121               12         2     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   80757                0         1     Junior
9       Bob   43  Marketing   49692                6         2  Mid-Level
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing  112409                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   41016                2         1     Junior
19  Charlie   30       Tech   95591                2         4     Junior


# 5Ô∏è‚É£ Overwrite all salaries for employees with < 3 years of experience to 35000.
#    - Use boolean indexing with .loc to do this.

In [73]:
df.loc[df["YearsExperience"] < 3 , "Salary" ] = 35000
df

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
1     Diana   23  Marketing  107121               12         2     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
9       Bob   43  Marketing   49692                6         2  Mid-Level
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 6Ô∏è‚É£ Compare using .loc and .iloc to select the same row:
#    - Select the 3rd row using .iloc
#    - Find its index value and use .loc to select the same row by label

In [74]:
# by .iloc
df.iloc[2]

Name                Ethan
Age                    45
Department           Tech
Salary             109479
YearsExperience        17
DeptCode                4
Seniority          Senior
Name: 2, dtype: object

In [75]:
# by loc
label_index = df.index[2]  # return 2
df.loc[label_index]

Name                Ethan
Age                    45
Department           Tech
Salary             109479
YearsExperience        17
DeptCode                4
Seniority          Senior
Name: 2, dtype: object


# 7Ô∏è‚É£ Check if there are any duplicate names in the dataset.
#    - If there are, show only those duplicated rows.

In [76]:
df[df["Name"].duplicated()]

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
3    George   51      Sales   59457               14         1     Senior
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 8Ô∏è‚É£ Sort the DataFrame by Salary in descending order.
#    - Then sort it by Department and within Department by Age.

In [77]:
df_sorted_bySalary = df.sort_values(by="Salary", ascending=False)
# df_sorted_bySalary
new_df = df_sorted_bySalary.sort_values(by=["Department", "Age"])
new_df

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
14   Hannah   36         HR   77065               10         3  Mid-Level
0    George   43         HR   75920               15         3     Senior
16    Diana   58         HR   51534               16         3     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
1     Diana   23  Marketing  107121               12         2     Senior
6     Ethan   42  Marketing  118953               14         2     Senior
9       Bob   43  Marketing   49692                6         2  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
18   Hannah   42      Sales   35000                2         1     Junior
10  Charlie   46      Sales   85758                8         1  Mid-Level
3    George   51      Sales   59457               14         1     Senior
15    Ethan   24       Tech   72606               18         4     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
19  Charlie   30       Tech   35000                2         4     Junior
13  Charlie   37       Tech  105697                7         4  Mid-Level
2     Ethan   45       Tech  109479               17         4     Senior
12  Charlie   49       Tech  111211               11         4     Senior
4   Charlie   59       Tech  106557               12         4     Senior


# 9Ô∏è‚É£ Slice the DataFrame to return rows 5 through 12 and columns 'Name', 'Salary'
#    - Try slicing using both label-based and position-based methods.

In [78]:
df.loc[5:12, ["Name", "Salary"]]

       Name  Salary
5    Hannah  117189
6     Ethan  118953
7     Ethan   92995
8    George   35000
9       Bob   49692
10  Charlie   85758
11   George   35000
12  Charlie  111211

In [79]:
df.iloc[5:12, [0, 3]]

       Name  Salary
5    Hannah  117189
6     Ethan  118953
7     Ethan   92995
8    George   35000
9       Bob   49692
10  Charlie   85758
11   George   35000


# üîü Find all rows where the name starts with 'A' or 'D'.
#    - Use string methods with .str accessor.

In [80]:
df[df["Name"].str.startswith(('A', 'D'))]

     Name  Age Department  Salary  YearsExperience  DeptCode Seniority
1   Diana   23  Marketing  107121               12         2    Senior
16  Diana   58         HR   51534               16         3    Senior

:
# 1Ô∏è‚É£1Ô∏è‚É£ Drop all rows where Age is below 25.
#     - Explain whether this modifies the DataFrame in place or returns a copy.

In [81]:
# This Modifies in place
# df.drop(df[df['Age'] < 25].index, inplace=True)
# This don't modify on the original df ---> df[df['Age'] >= 25]
new_filterd_df = df[df['Age'] >= 25]    # overwrite the original DataFrame

In [82]:
new_filterd_df

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
9       Bob   43  Marketing   49692                6         2  Mid-Level
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 1Ô∏è‚É£2Ô∏è‚É£ Use groupby to calculate the average salary per Department.
#     - Bonus: Show the average age and average experience too.

In [83]:
df.groupby("Department")[["Salary", "Age", "YearsExperience"]].mean().round(2)

              Salary    Age  YearsExperience
Department
HR          68173.00  45.67            13.67
Marketing   86825.00  38.83             8.67
Sales       53803.75  43.00             6.00
Tech        88706.71  38.86            10.57


# 1Ô∏è‚É£3Ô∏è‚É£ Use groupby to count how many employees are in each Department.

In [84]:
# df.groupby("Department")["Name"].count()
df.groupby("Department").size()

Department
HR           3
Marketing    6
Sales        4
Tech         7
dtype: int64


# 1Ô∏è‚É£4Ô∏è‚É£ Use .apply to normalize the Salary column (min-max scaling between 0 and 1).
#     - Bonus: Write your own normalization function and pass it to apply.

In [85]:
def min_max_nomralization(value):
  return (value - df["Salary"].min())  / (df["Salary"].max() - df["Salary"].min())

df["Normalize_Salary"] = df["Salary"].apply(min_max_nomralization)
df

,Name,Age,Department,Salary,YearsExperience,DeptCode,Seniority,Normalize_Salary
0,George,43,HR,75920,15,3,Senior,0.487416
1,Diana,23,Marketing,107121,12,2,Senior,0.859064
2,Ethan,45,Tech,109479,17,4,Senior,0.887151
3,George,51,Sales,59457,14,1,Senior,0.291318
4,Charlie,59,Tech,106557,12,4,Senior,0.852346
5,Hannah,23,Marketing,117189,8,2,Mid-Level,0.978988
6,Ethan,42,Marketing,118953,14,2,Senior,1.000000
7,Ethan,54,Marketing,92995,12,2,Senior,0.690803
8,George,33,Sales,35000,0,1,Junior,0.000000
9,Bob,43,Marketing,49692,6,2,Mid-Level,0.175003
10,Charlie,46,Sales,85758,8,1,Mid-Level,0.604600
11,George,48,Marketing,35000,0,2,Junior,0.000000
12,Charlie,49,Tech,111211,11,4,Senior,0.907782
13,Charlie,37,Tech,105697,7,4,Mid-Level,0.842102
14,Hannah,36,HR,77065,10,3,Mid-Level,0.501054
15,Ethan,24,Tech,72606,18,4,Senior,0.447941
16,Diana,58,HR,51534,16,3,Senior,0.196944
17,Hannah,28,Tech,80397,7,4,Mid-Level,0.540743
18,Hannah,42,Sales,35000,2,1,Junior,0.000000
19,Charlie,30,Tech,35000,2,4,Junior,0.000000


# 1Ô∏è‚É£5Ô∏è‚É£ Use boolean indexing to find all employees who:
#     - Are in 'HR' OR 'Tech', AND have > 5 years of experience.

# üîÅ For many of these tasks, try both .loc and .iloc to build intuition on their differences.

In [86]:
df.loc[(df["Department"].isin(["HR", "Tech"])) &  (df["YearsExperience"] > 5)]

,Name,Age,Department,Salary,YearsExperience,DeptCode,Seniority,Normalize_Salary
0,George,43,HR,75920,15,3,Senior,0.487416
2,Ethan,45,Tech,109479,17,4,Senior,0.887151
4,Charlie,59,Tech,106557,12,4,Senior,0.852346
12,Charlie,49,Tech,111211,11,4,Senior,0.907782
13,Charlie,37,Tech,105697,7,4,Mid-Level,0.842102
14,Hannah,36,HR,77065,10,3,Mid-Level,0.501054
15,Ethan,24,Tech,72606,18,4,Senior,0.447941
16,Diana,58,HR,51534,16,3,Senior,0.196944
17,Hannah,28,Tech,80397,7,4,Mid-Level,0.540743

In [67]:
mask = (df["Department"].isin(["HR", "Tech"])) & (df["YearsExperience"] > 5)
df.iloc[mask.values]

       Name  Age Department  Salary  YearsExperience  Normalize_Salary
0    George   43         HR   75920               15          0.447849
2     Ethan   45       Tech  109479               17          0.878440
4   Charlie   59       Tech  106557               12          0.840948
12  Charlie   49       Tech  111211               11          0.900663
13  Charlie   37       Tech  105697                7          0.829914
14   Hannah   36         HR   77065               10          0.462540
15    Ethan   24       Tech   72606               18          0.405327
16    Diana   58         HR   51534               16          0.134955
17   Hannah   28       Tech   80397                7          0.505293